import { APIError, type CollectionConfig, type Field } from 'payload'

import {
  FixedToolbarFeature,
  InlineToolbarFeature,
  lexicalEditor,
} from '@payloadcms/richtext-lexical'
import path from 'path'
import { fileURLToPath } from 'url'

import { anyone } from '../access/anyone'
import { editorOrOwner, isEditorOrOwner, ownerOnly } from '../access/roles'
import { adminText as tr } from '../i18n/admin'
import {
  MEDIA_PROCESSING_CONTEXT_KEY,
  queueMediaImageProcessing,
} from '../jobs/mediaTasks'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

const imageVariantFields = (): Field[] => [
  {
    name: 'url',
    type: 'text',
    admin: { hidden: true, readOnly: true },
  },
  {
    name: 'width',
    type: 'number',
    admin: { hidden: true, readOnly: true },
  },
  {
    name: 'height',
    type: 'number',
    admin: { hidden: true, readOnly: true },
  },
  {
    name: 'mimeType',
    type: 'text',
    admin: { hidden: true, readOnly: true },
  },
  {
    name: 'filesize',
    type: 'number',
    admin: { hidden: true, readOnly: true },
  },
  {
    name: 'filename',
    type: 'text',
    index: true,
    admin: { hidden: true, readOnly: true },
  },
]

const imageVariantField = (name: string): Field => ({
  name,
  type: 'group',
  admin: { hidden: true },
  fields: imageVariantFields(),
})

export const Media: CollectionConfig = {
  slug: 'media',
  labels: { singular: tr('Image', '图片', 'Imagen'), plural: tr('Image library', '素材库', 'Biblioteca de imágenes') },
  disableBulkDelete: true,
  disableBulkEdit: true,
  disableDuplicate: true,
  defaultSort: '-createdAt',
  lockDocuments: false,
  access: {
    create: editorOrOwner,
    delete: ownerOnly,
    read: anyone,
    update: editorOrOwner,
  },
  admin: {
    group: tr('Website content', '网站内容', 'Contenido del sitio'),
    defaultColumns: ['filename', 'updatedAt'],
    hideAPIURL: true,
    description: tr(
      'Product images are cropped to a square for the catalog. Banner images use the long banner variant on the homepage.',
      '商品图片会裁剪为正方形用于商品页；首页横幅会自动使用长比例版本。上传后可点击“编辑图片”调整裁剪区域。',
      'Las imágenes de producto se recortan en cuadrado para el catálogo y la portada usa automáticamente la versión panorámica. Después de subir una imagen puede editar el recorte.',
    ),
  },
  fields: [
    {
      name: 'migrationKey',
      type: 'text',
      unique: true,
      index: true,
      access: {
        create: () => false,
        read: ({ req }) => isEditorOrOwner(req),
        update: () => false,
      },
      admin: { hidden: true },
    },
    {
      name: 'alt',
      label: tr('Image description', '图片说明', 'Descripción de imagen'),
      type: 'text',
      localized: true,
      required: true,
      admin: {
        description: tr(
          'Describe the image for screen readers and search engines.',
          '请简要描述图片内容，供读屏软件和搜索引擎使用。',
          'Describa la imagen para lectores de pantalla y buscadores.',
        ),
      },
    },
    {
      name: 'caption',
      type: 'richText',
      localized: true,
      admin: {
        hidden: true,
      },
      editor: lexicalEditor({
        features: ({ rootFeatures }) => [
          ...rootFeatures,
          FixedToolbarFeature(),
          InlineToolbarFeature(),
        ],
      }),
    },
    // These fields keep the public API stable while allowing the expensive
    // derivatives to be generated by the media queue after the upload is saved.
    {
      name: 'sizes',
      type: 'group',
      admin: { hidden: true },
      fields: [
        imageVariantField('thumbnail'),
        imageVariantField('square'),
        // Legacy variants remain readable for existing records. New uploads
        // no longer generate them because no current page consumes them.
        imageVariantField('small'),
        imageVariantField('medium'),
        imageVariantField('large'),
        imageVariantField('xlarge'),
        imageVariantField('og'),
        imageVariantField('banner'),
      ],
    },
    {
      name: 'focalX',
      type: 'number',
      admin: { hidden: true, readOnly: true },
    },
    {
      name: 'focalY',
      type: 'number',
      admin: { hidden: true, readOnly: true },
    },
  ],
  hooks: {
    beforeValidate: [
      ({ data, req }) => {
        const file = req.file
        if (file && file.size > 15 * 1024 * 1024) {
          throw new APIError('图片不能超过 15 MB。', 400)
        }
        if ((data?.width && data.width > 12000) || (data?.height && data.height > 12000)) {
          throw new APIError('图片像素尺寸不能超过 12000 × 12000。', 400)
        }
        if (
          data?.width &&
          data?.height &&
          data.width * data.height > 40_000_000
        ) {
          throw new APIError('图片像素总数不能超过 4000 万。', 400)
        }
        return data
      },
    ],
    afterChange: [
      async ({ doc, req }) => {
        if (!req.file || req.context?.[MEDIA_PROCESSING_CONTEXT_KEY]) return doc

        try {
          await queueMediaImageProcessing(req, doc.id)
        } catch (error) {
          // A queue outage must not turn a successful original upload into a
          // failed admin save. The task can be retried by the regular runner.
          req.payload.logger.error({
            err: error,
            message: `Failed to queue image derivatives for media ${doc.id}`,
          })
        }

        return doc
      },
    ],
  },
  upload: {
    // Upload to the public/media directory in Next.js making them publicly accessible even outside of Payload
    staticDir: path.resolve(dirname, '../../public/media'),
    adminThumbnail: 'thumbnail',
    // Keep the original file and let editors adjust the crop from the admin UI.
    // Product, social, and banner derivatives are generated asynchronously so
    // the admin save is not blocked by multiple Sharp encodes and S3 uploads.
    crop: true,
    focalPoint: false,
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    pasteURL: false,
  },
}
