/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  timestamp,
  boolean,
  jsonb,
  numeric,
  type AnyPgColumn,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', [
  'en',
  'es',
  'ar',
  'de',
  'he',
  'ko',
  'pt',
  'zh-CN',
  'zh-TW',
])
export const enum_products_translation_status_locale = pgEnum(
  'enum_products_translation_status_locale',
  ['en', 'es', 'ar', 'de', 'he', 'ko', 'pt', 'zh-TW'],
)
export const enum_products_translation_status_status = pgEnum(
  'enum_products_translation_status_status',
  ['pending', 'translating', 'complete', 'partial', 'failed'],
)
export const enum_products_translation_status_mode = pgEnum(
  'enum_products_translation_status_mode',
  ['auto', 'manual'],
)
export const enum_products_workflow_state = pgEnum('enum_products_workflow_state', [
  'draft',
  'unlisted',
])
export const enum_products_status = pgEnum('enum_products_status', ['draft', 'published'])
export const enum__products_v_version_translation_status_locale = pgEnum(
  'enum__products_v_version_translation_status_locale',
  ['en', 'es', 'ar', 'de', 'he', 'ko', 'pt', 'zh-TW'],
)
export const enum__products_v_version_translation_status_status = pgEnum(
  'enum__products_v_version_translation_status_status',
  ['pending', 'translating', 'complete', 'partial', 'failed'],
)
export const enum__products_v_version_translation_status_mode = pgEnum(
  'enum__products_v_version_translation_status_mode',
  ['auto', 'manual'],
)
export const enum__products_v_version_workflow_state = pgEnum(
  'enum__products_v_version_workflow_state',
  ['draft', 'unlisted'],
)
export const enum__products_v_version_status = pgEnum('enum__products_v_version_status', [
  'draft',
  'published',
])
export const enum__products_v_published_locale = pgEnum('enum__products_v_published_locale', [
  'en',
  'es',
  'ar',
  'de',
  'he',
  'ko',
  'pt',
  'zh-CN',
  'zh-TW',
])
export const enum_posts_translation_status_locale = pgEnum('enum_posts_translation_status_locale', [
  'en',
  'es',
  'ar',
  'de',
  'he',
  'ko',
  'pt',
  'zh-TW',
])
export const enum_posts_translation_status_status = pgEnum('enum_posts_translation_status_status', [
  'pending',
  'translating',
  'complete',
  'partial',
  'failed',
])
export const enum_posts_translation_status_mode = pgEnum('enum_posts_translation_status_mode', [
  'auto',
  'manual',
])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum__posts_v_version_translation_status_locale = pgEnum(
  'enum__posts_v_version_translation_status_locale',
  ['en', 'es', 'ar', 'de', 'he', 'ko', 'pt', 'zh-TW'],
)
export const enum__posts_v_version_translation_status_status = pgEnum(
  'enum__posts_v_version_translation_status_status',
  ['pending', 'translating', 'complete', 'partial', 'failed'],
)
export const enum__posts_v_version_translation_status_mode = pgEnum(
  'enum__posts_v_version_translation_status_mode',
  ['auto', 'manual'],
)
export const enum__posts_v_version_status = pgEnum('enum__posts_v_version_status', [
  'draft',
  'published',
])
export const enum__posts_v_published_locale = pgEnum('enum__posts_v_published_locale', [
  'en',
  'es',
  'ar',
  'de',
  'he',
  'ko',
  'pt',
  'zh-CN',
  'zh-TW',
])
export const enum_users_role = pgEnum('enum_users_role', ['owner', 'editor'])
export const enum_redirects_to_type = pgEnum('enum_redirects_to_type', ['reference', 'custom'])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'translateProduct',
  'translatePost',
  'translateCompany',
  'schedulePublish',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'translateProduct',
  'translatePost',
  'translateCompany',
  'schedulePublish',
])
export const enum_company_translation_status_locale = pgEnum(
  'enum_company_translation_status_locale',
  ['en', 'es', 'ar', 'de', 'he', 'ko', 'pt', 'zh-TW'],
)
export const enum_company_translation_status_status = pgEnum(
  'enum_company_translation_status_status',
  ['pending', 'translating', 'complete', 'partial', 'failed'],
)
export const enum_company_translation_status_mode = pgEnum('enum_company_translation_status_mode', [
  'auto',
  'manual',
])
export const enum_customer_service_auth_scheme = pgEnum('enum_customer_service_auth_scheme', [
  'bearer',
  'raw',
  'x-api-key',
  'none',
])

export const products_specifications = pgTable(
  'products_specifications',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('products_specifications_order_idx').on(columns._order),
    index('products_specifications_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_specifications_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_specifications_locales = pgTable(
  'products_specifications_locales',
  {
    name: varchar('name'),
    value: varchar('value'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('products_specifications_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products_specifications.id],
      name: 'products_specifications_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_translation_status = pgTable(
  'products_translation_status',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    locale: enum_products_translation_status_locale('locale'),
    status: enum_products_translation_status_status('status'),
    mode: enum_products_translation_status_mode('mode'),
    sourceHash: varchar('source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    error: varchar('error'),
  },
  (columns) => [
    index('products_translation_status_order_idx').on(columns._order),
    index('products_translation_status_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_translation_status_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    sku: varchar('sku'),
    slug: varchar('slug'),
    workflowState: enum_products_workflow_state('workflow_state').default('draft'),
    translationSourceHash: varchar('translation_source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_products_status('_status').default('draft'),
  },
  (columns) => [
    index('products_sku_idx').on(columns.sku),
    uniqueIndex('products_slug_idx').on(columns.slug),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
    index('products__status_idx').on(columns._status),
  ],
)

export const products_locales = pgTable(
  'products_locales',
  {
    title: varchar('title'),
    shortDescription: varchar('short_description'),
    category: varchar('category'),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('products_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('products_rels_order_idx').on(columns.order),
    index('products_rels_parent_idx').on(columns.parent),
    index('products_rels_path_idx').on(columns.path),
    index('products_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'products_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_specifications = pgTable(
  '_products_v_version_specifications',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_specifications_order_idx').on(columns._order),
    index('_products_v_version_specifications_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_specifications_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_specifications_locales = pgTable(
  '_products_v_version_specifications_locales',
  {
    name: varchar('name'),
    value: varchar('value'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('_products_v_version_specifications_locales_locale_parent_id_').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v_version_specifications.id],
      name: '_products_v_version_specifications_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_version_translation_status = pgTable(
  '_products_v_version_translation_status',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    locale: enum__products_v_version_translation_status_locale('locale'),
    status: enum__products_v_version_translation_status_status('status'),
    mode: enum__products_v_version_translation_status_mode('mode'),
    sourceHash: varchar('source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    error: varchar('error'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_products_v_version_translation_status_order_idx').on(columns._order),
    index('_products_v_version_translation_status_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_translation_status_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v = pgTable(
  '_products_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    version_sku: varchar('version_sku'),
    version_slug: varchar('version_slug'),
    version_workflowState:
      enum__products_v_version_workflow_state('version_workflow_state').default('draft'),
    version_translationSourceHash: varchar('version_translation_source_hash'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__products_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__products_v_published_locale('published_locale'),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_products_v_parent_idx').on(columns.parent),
    index('_products_v_version_version_sku_idx').on(columns.version_sku),
    index('_products_v_version_version_slug_idx').on(columns.version_slug),
    index('_products_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_products_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_products_v_version_version__status_idx').on(columns.version__status),
    index('_products_v_created_at_idx').on(columns.createdAt),
    index('_products_v_updated_at_idx').on(columns.updatedAt),
    index('_products_v_snapshot_idx').on(columns.snapshot),
    index('_products_v_published_locale_idx').on(columns.publishedLocale),
    index('_products_v_latest_idx').on(columns.latest),
  ],
)

export const _products_v_locales = pgTable(
  '_products_v_locales',
  {
    version_title: varchar('version_title'),
    version_shortDescription: varchar('version_short_description'),
    version_category: varchar('version_category'),
    version_description: varchar('version_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('_products_v_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _products_v_rels = pgTable(
  '_products_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('_products_v_rels_order_idx').on(columns.order),
    index('_products_v_rels_parent_idx').on(columns.parent),
    index('_products_v_rels_path_idx').on(columns.path),
    index('_products_v_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_products_v.id],
      name: '_products_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: '_products_v_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const posts_populated_authors = pgTable(
  'posts_populated_authors',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name'),
  },
  (columns) => [
    index('posts_populated_authors_order_idx').on(columns._order),
    index('posts_populated_authors_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_populated_authors_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const posts_translation_status = pgTable(
  'posts_translation_status',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    locale: enum_posts_translation_status_locale('locale'),
    status: enum_posts_translation_status_status('status'),
    mode: enum_posts_translation_status_mode('mode'),
    sourceHash: varchar('source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    error: varchar('error'),
  },
  (columns) => [
    index('posts_translation_status_order_idx').on(columns._order),
    index('posts_translation_status_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_translation_status_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    generateSlug: boolean('generate_slug').default(true),
    slug: varchar('slug'),
    translationSourceHash: varchar('translation_source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => [
    index('posts_hero_image_idx').on(columns.heroImage),
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
    index('posts__status_idx').on(columns._status),
  ],
)

export const posts_locales = pgTable(
  'posts_locales',
  {
    title: varchar('title'),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    index('posts_meta_meta_image_idx').on(columns.meta_image, columns._locale),
    uniqueIndex('posts_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
    categoriesID: integer('categories_id'),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_posts_id_idx').on(columns.postsID),
    index('posts_rels_categories_id_idx').on(columns.categoriesID),
    index('posts_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'posts_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'posts_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'posts_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v_version_populated_authors = pgTable(
  '_posts_v_version_populated_authors',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    _uuid: varchar('_uuid'),
    name: varchar('name'),
  },
  (columns) => [
    index('_posts_v_version_populated_authors_order_idx').on(columns._order),
    index('_posts_v_version_populated_authors_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_version_populated_authors_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v_version_translation_status = pgTable(
  '_posts_v_version_translation_status',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    locale: enum__posts_v_version_translation_status_locale('locale'),
    status: enum__posts_v_version_translation_status_status('status'),
    mode: enum__posts_v_version_translation_status_mode('mode'),
    sourceHash: varchar('source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    error: varchar('error'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_posts_v_version_translation_status_order_idx').on(columns._order),
    index('_posts_v_version_translation_status_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_version_translation_status_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_heroImage: integer('version_hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_generateSlug: boolean('version_generate_slug').default(true),
    version_slug: varchar('version_slug'),
    version_translationSourceHash: varchar('version_translation_source_hash'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    snapshot: boolean('snapshot'),
    publishedLocale: enum__posts_v_published_locale('published_locale'),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_posts_v_parent_idx').on(columns.parent),
    index('_posts_v_version_version_hero_image_idx').on(columns.version_heroImage),
    index('_posts_v_version_version_slug_idx').on(columns.version_slug),
    index('_posts_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_posts_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_posts_v_version_version__status_idx').on(columns.version__status),
    index('_posts_v_created_at_idx').on(columns.createdAt),
    index('_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_posts_v_snapshot_idx').on(columns.snapshot),
    index('_posts_v_published_locale_idx').on(columns.publishedLocale),
    index('_posts_v_latest_idx').on(columns.latest),
    index('_posts_v_autosave_idx').on(columns.autosave),
  ],
)

export const _posts_v_locales = pgTable(
  '_posts_v_locales',
  {
    version_title: varchar('version_title'),
    version_excerpt: varchar('version_excerpt'),
    version_content: jsonb('version_content'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_description: varchar('version_meta_description'),
    version_meta_image: integer('version_meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    index('_posts_v_version_meta_version_meta_image_idx').on(
      columns.version_meta_image,
      columns._locale,
    ),
    uniqueIndex('_posts_v_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _posts_v_rels = pgTable(
  '_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
    categoriesID: integer('categories_id'),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('_posts_v_rels_order_idx').on(columns.order),
    index('_posts_v_rels_parent_idx').on(columns.parent),
    index('_posts_v_rels_path_idx').on(columns.path),
    index('_posts_v_rels_posts_id_idx').on(columns.postsID),
    index('_posts_v_rels_categories_id_idx').on(columns.categoriesID),
    index('_posts_v_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: '_posts_v_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: '_posts_v_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: '_posts_v_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    migrationKey: varchar('migration_key'),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
    sizes_square_url: varchar('sizes_square_url'),
    sizes_square_width: numeric('sizes_square_width', { mode: 'number' }),
    sizes_square_height: numeric('sizes_square_height', { mode: 'number' }),
    sizes_square_mimeType: varchar('sizes_square_mime_type'),
    sizes_square_filesize: numeric('sizes_square_filesize', { mode: 'number' }),
    sizes_square_filename: varchar('sizes_square_filename'),
    sizes_small_url: varchar('sizes_small_url'),
    sizes_small_width: numeric('sizes_small_width', { mode: 'number' }),
    sizes_small_height: numeric('sizes_small_height', { mode: 'number' }),
    sizes_small_mimeType: varchar('sizes_small_mime_type'),
    sizes_small_filesize: numeric('sizes_small_filesize', { mode: 'number' }),
    sizes_small_filename: varchar('sizes_small_filename'),
    sizes_medium_url: varchar('sizes_medium_url'),
    sizes_medium_width: numeric('sizes_medium_width', { mode: 'number' }),
    sizes_medium_height: numeric('sizes_medium_height', { mode: 'number' }),
    sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
    sizes_medium_filesize: numeric('sizes_medium_filesize', { mode: 'number' }),
    sizes_medium_filename: varchar('sizes_medium_filename'),
    sizes_large_url: varchar('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width', { mode: 'number' }),
    sizes_large_height: numeric('sizes_large_height', { mode: 'number' }),
    sizes_large_mimeType: varchar('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize', { mode: 'number' }),
    sizes_large_filename: varchar('sizes_large_filename'),
    sizes_xlarge_url: varchar('sizes_xlarge_url'),
    sizes_xlarge_width: numeric('sizes_xlarge_width', { mode: 'number' }),
    sizes_xlarge_height: numeric('sizes_xlarge_height', { mode: 'number' }),
    sizes_xlarge_mimeType: varchar('sizes_xlarge_mime_type'),
    sizes_xlarge_filesize: numeric('sizes_xlarge_filesize', { mode: 'number' }),
    sizes_xlarge_filename: varchar('sizes_xlarge_filename'),
    sizes_og_url: varchar('sizes_og_url'),
    sizes_og_width: numeric('sizes_og_width', { mode: 'number' }),
    sizes_og_height: numeric('sizes_og_height', { mode: 'number' }),
    sizes_og_mimeType: varchar('sizes_og_mime_type'),
    sizes_og_filesize: numeric('sizes_og_filesize', { mode: 'number' }),
    sizes_og_filename: varchar('sizes_og_filename'),
  },
  (columns) => [
    uniqueIndex('media_migration_key_idx').on(columns.migrationKey),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_square_sizes_square_filename_idx').on(columns.sizes_square_filename),
    index('media_sizes_small_sizes_small_filename_idx').on(columns.sizes_small_filename),
    index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename),
    index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename),
    index('media_sizes_xlarge_sizes_xlarge_filename_idx').on(columns.sizes_xlarge_filename),
    index('media_sizes_og_sizes_og_filename_idx').on(columns.sizes_og_filename),
  ],
)

export const media_locales = pgTable(
  'media_locales',
  {
    alt: varchar('alt').notNull(),
    caption: jsonb('caption'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('media_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [media.id],
      name: 'media_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories_breadcrumbs = pgTable(
  'categories_breadcrumbs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _locale: enum__locales('_locale').notNull(),
    id: varchar('id').primaryKey(),
    doc: integer('doc_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    label: varchar('label'),
  },
  (columns) => [
    index('categories_breadcrumbs_order_idx').on(columns._order),
    index('categories_breadcrumbs_parent_id_idx').on(columns._parentID),
    index('categories_breadcrumbs_locale_idx').on(columns._locale),
    index('categories_breadcrumbs_doc_idx').on(columns.doc),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_breadcrumbs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    generateSlug: boolean('generate_slug').default(true),
    slug: varchar('slug').notNull(),
    parent: integer('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_parent_idx').on(columns.parent),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    role: enum_users_role('role').notNull().default('owner'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const audit_events = pgTable(
  'audit_events',
  {
    id: serial('id').primaryKey(),
    actor: integer('actor_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    action: varchar('action').notNull(),
    entityType: varchar('entity_type').notNull(),
    entityId: varchar('entity_id'),
    summary: varchar('summary').notNull(),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('audit_events_actor_idx').on(columns.actor),
    index('audit_events_action_idx').on(columns.action),
    index('audit_events_entity_type_idx').on(columns.entityType),
    index('audit_events_updated_at_idx').on(columns.updatedAt),
    index('audit_events_created_at_idx').on(columns.createdAt),
  ],
)

export const redirects = pgTable(
  'redirects',
  {
    id: serial('id').primaryKey(),
    from: varchar('from').notNull(),
    to_type: enum_redirects_to_type('to_type').default('reference'),
    to_url: varchar('to_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('redirects_from_idx').on(columns.from),
    index('redirects_updated_at_idx').on(columns.updatedAt),
    index('redirects_created_at_idx').on(columns.createdAt),
  ],
)

export const redirects_rels = pgTable(
  'redirects_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
  },
  (columns) => [
    index('redirects_rels_order_idx').on(columns.order),
    index('redirects_rels_parent_idx').on(columns.parent),
    index('redirects_rels_path_idx').on(columns.path),
    index('redirects_rels_posts_id_idx').on(columns.postsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [redirects.id],
      name: 'redirects_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'redirects_rels_posts_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
    categoriesID: integer('categories_id'),
    usersID: integer('users_id'),
    'audit-eventsID': integer('audit_events_id'),
    redirectsID: integer('redirects_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_audit_events_id_idx').on(columns['audit-eventsID']),
    index('payload_locked_documents_rels_redirects_id_idx').on(columns.redirectsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['audit-eventsID']],
      foreignColumns: [audit_events.id],
      name: 'payload_locked_documents_rels_audit_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['redirectsID']],
      foreignColumns: [redirects.id],
      name: 'payload_locked_documents_rels_redirects_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const company_highlights = pgTable(
  'company_highlights',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('company_highlights_order_idx').on(columns._order),
    index('company_highlights_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [company.id],
      name: 'company_highlights_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const company_highlights_locales = pgTable(
  'company_highlights_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('company_highlights_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [company_highlights.id],
      name: 'company_highlights_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const company_translation_status = pgTable(
  'company_translation_status',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    locale: enum_company_translation_status_locale('locale').notNull(),
    status: enum_company_translation_status_status('status').notNull(),
    mode: enum_company_translation_status_mode('mode').notNull(),
    sourceHash: varchar('source_hash'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    error: varchar('error'),
  },
  (columns) => [
    index('company_translation_status_order_idx').on(columns._order),
    index('company_translation_status_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [company.id],
      name: 'company_translation_status_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const company = pgTable('company', {
  id: serial('id').primaryKey(),
  brandName: varchar('brand_name').notNull(),
  contact_email: varchar('contact_email').notNull(),
  contact_phone: varchar('contact_phone'),
  contact_wechat: varchar('contact_wechat'),
  translationSourceHash: varchar('translation_source_hash'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const company_locales = pgTable(
  'company_locales',
  {
    heroTitle: varchar('hero_title').notNull(),
    heroDescription: varchar('hero_description').notNull(),
    aboutTitle: varchar('about_title'),
    aboutDescription: varchar('about_description'),
    contact_address: varchar('contact_address'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('company_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [company.id],
      name: 'company_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const customer_service = pgTable('customer_service', {
  id: serial('id').primaryKey(),
  enabled: boolean('enabled').default(true),
  apiUrl: varchar('api_url'),
  apiKey: varchar('api_key'),
  authScheme: enum_customer_service_auth_scheme('auth_scheme').notNull().default('bearer'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const homepage = pgTable('homepage', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const homepage_rels = pgTable(
  'homepage_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
  },
  (columns) => [
    index('homepage_rels_order_idx').on(columns.order),
    index('homepage_rels_parent_idx').on(columns.parent),
    index('homepage_rels_path_idx').on(columns.path),
    index('homepage_rels_products_id_idx').on(columns.productsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [homepage.id],
      name: 'homepage_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'homepage_rels_products_fk',
    }).onDelete('cascade'),
  ],
)

export const relations_products_specifications_locales = relations(
  products_specifications_locales,
  ({ one }) => ({
    _parentID: one(products_specifications, {
      fields: [products_specifications_locales._parentID],
      references: [products_specifications.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_products_specifications = relations(
  products_specifications,
  ({ one, many }) => ({
    _parentID: one(products, {
      fields: [products_specifications._parentID],
      references: [products.id],
      relationName: 'specifications',
    }),
    _locales: many(products_specifications_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_products_translation_status = relations(
  products_translation_status,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_translation_status._parentID],
      references: [products.id],
      relationName: 'translationStatus',
    }),
  }),
)
export const relations_products_locales = relations(products_locales, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_locales._parentID],
    references: [products.id],
    relationName: '_locales',
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_products = relations(products, ({ many }) => ({
  specifications: many(products_specifications, {
    relationName: 'specifications',
  }),
  translationStatus: many(products_translation_status, {
    relationName: 'translationStatus',
  }),
  _locales: many(products_locales, {
    relationName: '_locales',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations__products_v_version_specifications_locales = relations(
  _products_v_version_specifications_locales,
  ({ one }) => ({
    _parentID: one(_products_v_version_specifications, {
      fields: [_products_v_version_specifications_locales._parentID],
      references: [_products_v_version_specifications.id],
      relationName: '_locales',
    }),
  }),
)
export const relations__products_v_version_specifications = relations(
  _products_v_version_specifications,
  ({ one, many }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_specifications._parentID],
      references: [_products_v.id],
      relationName: 'version_specifications',
    }),
    _locales: many(_products_v_version_specifications_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations__products_v_version_translation_status = relations(
  _products_v_version_translation_status,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_translation_status._parentID],
      references: [_products_v.id],
      relationName: 'version_translationStatus',
    }),
  }),
)
export const relations__products_v_locales = relations(_products_v_locales, ({ one }) => ({
  _parentID: one(_products_v, {
    fields: [_products_v_locales._parentID],
    references: [_products_v.id],
    relationName: '_locales',
  }),
}))
export const relations__products_v_rels = relations(_products_v_rels, ({ one }) => ({
  parent: one(_products_v, {
    fields: [_products_v_rels.parent],
    references: [_products_v.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [_products_v_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations__products_v = relations(_products_v, ({ one, many }) => ({
  parent: one(products, {
    fields: [_products_v.parent],
    references: [products.id],
    relationName: 'parent',
  }),
  version_specifications: many(_products_v_version_specifications, {
    relationName: 'version_specifications',
  }),
  version_translationStatus: many(_products_v_version_translation_status, {
    relationName: 'version_translationStatus',
  }),
  _locales: many(_products_v_locales, {
    relationName: '_locales',
  }),
  _rels: many(_products_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_posts_populated_authors = relations(posts_populated_authors, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_populated_authors._parentID],
    references: [posts.id],
    relationName: 'populatedAuthors',
  }),
}))
export const relations_posts_translation_status = relations(
  posts_translation_status,
  ({ one }) => ({
    _parentID: one(posts, {
      fields: [posts_translation_status._parentID],
      references: [posts.id],
      relationName: 'translationStatus',
    }),
  }),
)
export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: '_locales',
  }),
  meta_image: one(media, {
    fields: [posts_locales.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [posts_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
  categoriesID: one(categories, {
    fields: [posts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  usersID: one(users, {
    fields: [posts_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [posts.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  populatedAuthors: many(posts_populated_authors, {
    relationName: 'populatedAuthors',
  }),
  translationStatus: many(posts_translation_status, {
    relationName: 'translationStatus',
  }),
  _locales: many(posts_locales, {
    relationName: '_locales',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__posts_v_version_populated_authors = relations(
  _posts_v_version_populated_authors,
  ({ one }) => ({
    _parentID: one(_posts_v, {
      fields: [_posts_v_version_populated_authors._parentID],
      references: [_posts_v.id],
      relationName: 'version_populatedAuthors',
    }),
  }),
)
export const relations__posts_v_version_translation_status = relations(
  _posts_v_version_translation_status,
  ({ one }) => ({
    _parentID: one(_posts_v, {
      fields: [_posts_v_version_translation_status._parentID],
      references: [_posts_v.id],
      relationName: 'version_translationStatus',
    }),
  }),
)
export const relations__posts_v_locales = relations(_posts_v_locales, ({ one }) => ({
  _parentID: one(_posts_v, {
    fields: [_posts_v_locales._parentID],
    references: [_posts_v.id],
    relationName: '_locales',
  }),
  version_meta_image: one(media, {
    fields: [_posts_v_locales.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [_posts_v_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
  categoriesID: one(categories, {
    fields: [_posts_v_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  usersID: one(users, {
    fields: [_posts_v_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_heroImage: one(media, {
    fields: [_posts_v.version_heroImage],
    references: [media.id],
    relationName: 'version_heroImage',
  }),
  version_populatedAuthors: many(_posts_v_version_populated_authors, {
    relationName: 'version_populatedAuthors',
  }),
  version_translationStatus: many(_posts_v_version_translation_status, {
    relationName: 'version_translationStatus',
  }),
  _locales: many(_posts_v_locales, {
    relationName: '_locales',
  }),
  _rels: many(_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_media_locales = relations(media_locales, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_locales._parentID],
    references: [media.id],
    relationName: '_locales',
  }),
}))
export const relations_media = relations(media, ({ many }) => ({
  _locales: many(media_locales, {
    relationName: '_locales',
  }),
}))
export const relations_categories_breadcrumbs = relations(categories_breadcrumbs, ({ one }) => ({
  _parentID: one(categories, {
    fields: [categories_breadcrumbs._parentID],
    references: [categories.id],
    relationName: 'breadcrumbs',
  }),
  doc: one(categories, {
    fields: [categories_breadcrumbs.doc],
    references: [categories.id],
    relationName: 'doc',
  }),
}))
export const relations_categories = relations(categories, ({ one, many }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  breadcrumbs: many(categories_breadcrumbs, {
    relationName: 'breadcrumbs',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_audit_events = relations(audit_events, ({ one }) => ({
  actor: one(users, {
    fields: [audit_events.actor],
    references: [users.id],
    relationName: 'actor',
  }),
}))
export const relations_redirects_rels = relations(redirects_rels, ({ one }) => ({
  parent: one(redirects, {
    fields: [redirects_rels.parent],
    references: [redirects.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [redirects_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
}))
export const relations_redirects = relations(redirects, ({ many }) => ({
  _rels: many(redirects_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'audit-eventsID': one(audit_events, {
      fields: [payload_locked_documents_rels['audit-eventsID']],
      references: [audit_events.id],
      relationName: 'audit-events',
    }),
    redirectsID: one(redirects, {
      fields: [payload_locked_documents_rels.redirectsID],
      references: [redirects.id],
      relationName: 'redirects',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_company_highlights_locales = relations(
  company_highlights_locales,
  ({ one }) => ({
    _parentID: one(company_highlights, {
      fields: [company_highlights_locales._parentID],
      references: [company_highlights.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_company_highlights = relations(company_highlights, ({ one, many }) => ({
  _parentID: one(company, {
    fields: [company_highlights._parentID],
    references: [company.id],
    relationName: 'highlights',
  }),
  _locales: many(company_highlights_locales, {
    relationName: '_locales',
  }),
}))
export const relations_company_translation_status = relations(
  company_translation_status,
  ({ one }) => ({
    _parentID: one(company, {
      fields: [company_translation_status._parentID],
      references: [company.id],
      relationName: 'translationStatus',
    }),
  }),
)
export const relations_company_locales = relations(company_locales, ({ one }) => ({
  _parentID: one(company, {
    fields: [company_locales._parentID],
    references: [company.id],
    relationName: '_locales',
  }),
}))
export const relations_company = relations(company, ({ many }) => ({
  highlights: many(company_highlights, {
    relationName: 'highlights',
  }),
  translationStatus: many(company_translation_status, {
    relationName: 'translationStatus',
  }),
  _locales: many(company_locales, {
    relationName: '_locales',
  }),
}))
export const relations_customer_service = relations(customer_service, () => ({}))
export const relations_homepage_rels = relations(homepage_rels, ({ one }) => ({
  parent: one(homepage, {
    fields: [homepage_rels.parent],
    references: [homepage.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [homepage_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
}))
export const relations_homepage = relations(homepage, ({ many }) => ({
  _rels: many(homepage_rels, {
    relationName: '_rels',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_products_translation_status_locale: typeof enum_products_translation_status_locale
  enum_products_translation_status_status: typeof enum_products_translation_status_status
  enum_products_translation_status_mode: typeof enum_products_translation_status_mode
  enum_products_workflow_state: typeof enum_products_workflow_state
  enum_products_status: typeof enum_products_status
  enum__products_v_version_translation_status_locale: typeof enum__products_v_version_translation_status_locale
  enum__products_v_version_translation_status_status: typeof enum__products_v_version_translation_status_status
  enum__products_v_version_translation_status_mode: typeof enum__products_v_version_translation_status_mode
  enum__products_v_version_workflow_state: typeof enum__products_v_version_workflow_state
  enum__products_v_version_status: typeof enum__products_v_version_status
  enum__products_v_published_locale: typeof enum__products_v_published_locale
  enum_posts_translation_status_locale: typeof enum_posts_translation_status_locale
  enum_posts_translation_status_status: typeof enum_posts_translation_status_status
  enum_posts_translation_status_mode: typeof enum_posts_translation_status_mode
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_translation_status_locale: typeof enum__posts_v_version_translation_status_locale
  enum__posts_v_version_translation_status_status: typeof enum__posts_v_version_translation_status_status
  enum__posts_v_version_translation_status_mode: typeof enum__posts_v_version_translation_status_mode
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum__posts_v_published_locale: typeof enum__posts_v_published_locale
  enum_users_role: typeof enum_users_role
  enum_redirects_to_type: typeof enum_redirects_to_type
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  enum_company_translation_status_locale: typeof enum_company_translation_status_locale
  enum_company_translation_status_status: typeof enum_company_translation_status_status
  enum_company_translation_status_mode: typeof enum_company_translation_status_mode
  enum_customer_service_auth_scheme: typeof enum_customer_service_auth_scheme
  products_specifications: typeof products_specifications
  products_specifications_locales: typeof products_specifications_locales
  products_translation_status: typeof products_translation_status
  products: typeof products
  products_locales: typeof products_locales
  products_rels: typeof products_rels
  _products_v_version_specifications: typeof _products_v_version_specifications
  _products_v_version_specifications_locales: typeof _products_v_version_specifications_locales
  _products_v_version_translation_status: typeof _products_v_version_translation_status
  _products_v: typeof _products_v
  _products_v_locales: typeof _products_v_locales
  _products_v_rels: typeof _products_v_rels
  posts_populated_authors: typeof posts_populated_authors
  posts_translation_status: typeof posts_translation_status
  posts: typeof posts
  posts_locales: typeof posts_locales
  posts_rels: typeof posts_rels
  _posts_v_version_populated_authors: typeof _posts_v_version_populated_authors
  _posts_v_version_translation_status: typeof _posts_v_version_translation_status
  _posts_v: typeof _posts_v
  _posts_v_locales: typeof _posts_v_locales
  _posts_v_rels: typeof _posts_v_rels
  media: typeof media
  media_locales: typeof media_locales
  categories_breadcrumbs: typeof categories_breadcrumbs
  categories: typeof categories
  users_sessions: typeof users_sessions
  users: typeof users
  audit_events: typeof audit_events
  redirects: typeof redirects
  redirects_rels: typeof redirects_rels
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  company_highlights: typeof company_highlights
  company_highlights_locales: typeof company_highlights_locales
  company_translation_status: typeof company_translation_status
  company: typeof company
  company_locales: typeof company_locales
  customer_service: typeof customer_service
  homepage: typeof homepage
  homepage_rels: typeof homepage_rels
  relations_products_specifications_locales: typeof relations_products_specifications_locales
  relations_products_specifications: typeof relations_products_specifications
  relations_products_translation_status: typeof relations_products_translation_status
  relations_products_locales: typeof relations_products_locales
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations__products_v_version_specifications_locales: typeof relations__products_v_version_specifications_locales
  relations__products_v_version_specifications: typeof relations__products_v_version_specifications
  relations__products_v_version_translation_status: typeof relations__products_v_version_translation_status
  relations__products_v_locales: typeof relations__products_v_locales
  relations__products_v_rels: typeof relations__products_v_rels
  relations__products_v: typeof relations__products_v
  relations_posts_populated_authors: typeof relations_posts_populated_authors
  relations_posts_translation_status: typeof relations_posts_translation_status
  relations_posts_locales: typeof relations_posts_locales
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations__posts_v_version_populated_authors: typeof relations__posts_v_version_populated_authors
  relations__posts_v_version_translation_status: typeof relations__posts_v_version_translation_status
  relations__posts_v_locales: typeof relations__posts_v_locales
  relations__posts_v_rels: typeof relations__posts_v_rels
  relations__posts_v: typeof relations__posts_v
  relations_media_locales: typeof relations_media_locales
  relations_media: typeof relations_media
  relations_categories_breadcrumbs: typeof relations_categories_breadcrumbs
  relations_categories: typeof relations_categories
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_audit_events: typeof relations_audit_events
  relations_redirects_rels: typeof relations_redirects_rels
  relations_redirects: typeof relations_redirects
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_company_highlights_locales: typeof relations_company_highlights_locales
  relations_company_highlights: typeof relations_company_highlights
  relations_company_translation_status: typeof relations_company_translation_status
  relations_company_locales: typeof relations_company_locales
  relations_company: typeof relations_company
  relations_customer_service: typeof relations_customer_service
  relations_homepage_rels: typeof relations_homepage_rels
  relations_homepage: typeof relations_homepage
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
